### ISSUE TITLE
Replay specific test from metadata or start from iteration

### ISSUE THREAD

**Issue by cweb** [aoh/radamsa#16]
Can you make it so we can replay a specific test from the metadata log?  Or, so we can start fuzzing at a certain iteration given a seed value?

**Comment by aoh** [comment]
The latter sounds more generic. I haven't needed such functionality, but do see why that might come in handy. Will add.

**Comment by aoh** [comment]
$ echo "HAL 9000" | radamsa --seed 0 -n 20 -o /tmp/rad-%n
$ echo "HAL 9000" | radamsa --seed 0 --seek 12 -n 4 | md5sum
a63688cec88bd2ab6d411e2d90b8e5f8  -
$ cat /tmp/rad-1[2-5] | md5sum
a63688cec88bd2ab6d411e2d90b8e5f8  -

Note that searching is O(n), because learning and data gathering are combined with the generation phase.
