### ISSUE TITLE
Adding original filename to output filename

### ISSUE THREAD

**Issue by dwendt** [aoh/radamsa#19]
Hey, I'm fuzzing something that relies on file extensions and I'm using a large number of file types to fuzz it from my test cases (i.e. samples are at `../tests/*` and look like `from_twitter.exe`, `setup.bat`, `malware.yaml`. `pick-suffix` only takes the first suffix it finds for the first file and uses that as `%s` for every output file. 

So, I tried to add an output formatter `%p` that will insert the whole filename that was used to generate the test case. I thought the best way to do this would be to use `get meta 'source` but I can't figure out how `'source` is set and it is occasionally not set at all for some test cases (I assume this is when it splices files together?).

This attempt results in a large number of test cases with an unknown source file suffix (`muted` in my commit). Any ideas on how that could be better retrieved?

https://github.com/dwendt/radamsa/commit/c88a8f0fb725c530751e18057d2cb9de7ea65616

Example meta of where it fails to grab the source~

```
utf8-insert: 3, muta-num: 5, generator: jump, nth: 22587, path: "/cygdrive/m/22587_unk", head: "/home/qt/_test/test.sis", output: file-writer, length: 827, tail: "/home/qt/_test/test.tar.gz", pattern: many-dec
```

It seems to me that it occurs in cases where the file is a combination of head/tail files. I'm unsure if the best solution should combine the head/tail filenames or simply select one based on the formatter (`%0p` / `%1p`) or randomly.

**Comment by aoh** [comment]
Hi, 

Typically you have different instances of radamsa running for each file type. A way to set the suffix based on the sample(s) used, if any, does make sense though. Feel free to make a pull request, if you have time to work on it.

You could simplify fname-suffix to something like `(define (path-suffix path default) (let ((suf (s/.*\.([^./]+)$/\3/ path))) (if (equal? suf path) default suf)))`, append it string->list:ed to (cdr tl) in output path construction as you did (note that you don't need a list of paths), change the default source from `/muted` to something like `unknown.bin`, and optionally swap 'head to 'source in `jump-streamer` in rad/generators.scm.

Generators are responsible for producing streams of data for mutation. They set the initial information in meta. `file-streamer` is the one streaming one file, `jump-streamer` swaps from one file to another, and there are also generators for random data and stdin streaming. A default suffix is still needed, because the latter two also don't set a 'source in meta.

**Comment by aoh** [comment]
I forgot to add a note about this to NEWS before tagging 0.5. It'll be visible in 0.6.

Thanks for suggesting a useful feature.
