### ISSUE TITLE
Request to remove owl-lisp cloning during radamsa build

### ISSUE THREAD

**Issue by brarcher** [aoh/radamsa#5]
In the release of Radamsa 0.3, available here:

  https://ouspg.googlecode.com/files/radamsa-0.3.tar.gz

the compilation step consisted of compiling the included radamsa.c file. This allowed one to download a release and compile without downloading anything else.

I noticed that in Radamsa 0.4 that the makefile now will clone the owl-lisp git repo, build it, then use owl-lisp to generate radamsa.c before compiling it. This can lead to build issues, as owl-lisp may not be accessible at the time or the version of own-lisp downloaded over git may not be a version compatible with Radamsa 0.4. 

As a concrete example, I found myself unable to build Radamsa 0.4 because the latest revision of owl-lisp built but was unable to generate radamsa.c :

```
$ cd radamsa-0.4/
$ make
make get-owl
make[1]: Entering directory `/home/brarcher/tmp/radamsa-0.4'
# fetching and building owl to build radamsa
# this may take a few minutes on first build
git clone https://github.com/aoh/owl-lisp.git
Cloning into 'owl-lisp'...
remote: Counting objects: 4485, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4485 (delta 0), reused 0 (delta 0), pack-reused 4481
Receiving objects: 100% (4485/4485), 6.36 MiB | 0 bytes/s, done.
Resolving deltas: 100% (3076/3076), done.
Checking connectivity... done.
cd owl-lisp && git pull 
Already up-to-date.
cd owl-lisp && make
make[2]: Entering directory `/home/brarcher/tmp/radamsa-0.4/owl-lisp'
...
make[2]: Leaving directory `/home/brarcher/tmp/radamsa-0.4/owl-lisp'
make[1]: Leaving directory `/home/brarcher/tmp/radamsa-0.4'
owl-lisp/bin/ol -O2 -o radamsa.c rad/main.scm
Cannot compile rad/main.scm because  
  Library (rad main) failed: 
    Failed to load (rad output) because 
      Library (rad output) failed: 
        Definition of tcp-client failed because 
          What is 'sleeper-id'? 
make: *** [radamsa.c] Error 2
```

Kindly consider one of the following alternatives:
1) For releases of Radamsa package the generated radamsa.c file and avoid the owl-lisp dependency.
2) Package an appropriate version of owl-lisp in the Radamsa package
- also consider a way to only compile owl-lisp instead of also running its unit tests
  3) Search for owl-lisp on the system with a configure script or a CMake script and link against it

Thank you for your consideration.

**Comment by aoh** [comment]
Hi, 

Good points and thanks for reminding me about this issue. Radamsa.c was included in previous releases specifically to avoid these issues and extra dependency on owl, but Google Code shut down, Radamsa migrated to Github, and I hadn't figured out when releasing 0.4 how to add separate tarballs or binaries to/as the release.

A temporary solution was to put the downloads with signatures to http://haltp.org/download, and you can also do $ make build_radamsa, which by default uses /usr/bin/ol, to avoid a local build. 

Radamsa 0.5 should come out soonish after the current IO changes are done in Owl, an easy solution would be to include and update the prebuilt C code at each release. The Makefile is written so that owl is cloned only if radamsa.c needs to be rebuilt, so checking out with a release tag or downloading a prebuilt package would then cause no owl cloning.

Doing a quick build of owl is also a good idea. If you are using a local checkout, you probably don't want to do a full build. E.g., by using:

``` Make
local_radamsa:
   -git clone https://github.com/aoh/owl-lisp.git
   -cd owl-lisp && git pull 
   cd owl-lisp && make bin/vm
   owl-lisp/bin/vm owl-lisp/fasl/init.fasl -O2 -o radamsa.c rad/main.scm
```

it takes about 8 seconds to build Radamsa on my machine.

**Comment by aoh** [comment]
Radamsa now fetches a tagged version of owl and only does a minimal build. Will have to remember to add the prebuilt C code for next release, but this issue is now fixed.

Thanks for filing the issue. Let me know if you run into issues with the fix.

**Comment by brarcher** [comment]
v0.5 was released today and I gave it a look. I noticed that there is no artifact attached to the release which contains a prebuilt C code file for Radamsa. Is there interest in uploading a tarball which contains the release as well as a pre-generated radamsa.c file?

Thank you for your consideration.

**Comment by aoh** [comment]
Github releases might be a solution to this. I didn't have time to check out how they work yesterday though, so the current release tarball is just autogenerated from the tag for now.

**Comment by aoh** [comment]
Yes, it seems to be easy to add custom tarballs along with releases. The default radamsa-0.5.tar.gz download now has radamsa.c again, so the build does not depend on owl. If the actual sources are altered, only then the correct version of owl is loaded and radamsa.c is rebuilt.

**Comment by brarcher** [comment]
Awesome! Thanks!
